import Link from "next/link";
import { LeaguePortal } from "@/components/league-portal";
import audit from "../../../data/keeper-audit.json";
import readinessAudit from "../../../data/keeper-readiness-audit.json";
import { leagueData } from "../../lib/league-data";
const display=(value:unknown)=>value===null?"Unknown":typeof value==="number"?"Round "+value:String(value).replaceAll("_"," ");
export default function AuditPage() {
 const totals=audit.replay2025.summary;
 const exceptions=audit.replay2025.rows.filter(row=>row.status!=="match");
 return <LeaguePortal report={<div className="audit-content">
 <p className="eyebrow">HISTORICAL KEEPER CHECK</p>
 <h1 style={{margin:"10px 0 18px"}}>Show the math</h1>
 <p style={{maxWidth:800,fontSize:18,lineHeight:1.6}}>Independent calculations reproduce <strong>{totals.matched} of {totals.total}</strong> canonical 2025 keeper-cost records. One record differs and one player has conflicting source costs. Your later rulings remain separate from the historical comparison.</p>
 <section className="panel" style={{margin:"28px 0",padding:24}}>
 <p className="eyebrow">UPCOMING SEASON · REVIEW UPDATED OCTOBER 3, 2026</p><h2 style={{margin:"10px 0 16px"}}>2026 keeper readiness review</h2>
 <p style={{lineHeight:1.8}}>All <strong>{readinessAudit.summary.rosterPlayers} roster profiles</strong> agree numerically with a recomputation from the approved 2025 nominal-cost baseline and marked draft. No upcoming cost or tenure changes were needed. This checks consistency with the approved baseline; the source records for earlier historical transfers remain preserved.</p>
 <p style={{marginTop:14,lineHeight:1.8}}>Explicit 2024 fresh-draft and 2025 retention records support <strong>{readinessAudit.supportedConfirmations.length} previously inferred tenures</strong>. The established rule that an undrafted season counts as tenure one confirms the remaining <strong>{readinessAudit.ruleConfirmedProfiles.length} profiles</strong>, including Josh Hart and Quentin Grimes. All {readinessAudit.summary.totalSupportedConfirmations} reviewed profiles have supporting evidence; no keeper-rule decisions remain outstanding in this review.</p>
 <p style={{marginTop:14,lineHeight:1.8}}>This audit records the rule and historical evidence. Current verification and items to reconcile are shown in the <Link href="/">live league records</Link>.</p>
 <details style={{marginTop:20}}><summary style={{cursor:"pointer",fontWeight:700}}>Inspect the eleven evidence-supported confirmations</summary><div className="table-wrap"><table className="data-table"><thead><tr><th scope="col">Player</th><th scope="col">2026 base</th><th scope="col">Completed tenure</th><th scope="col">Supporting evidence</th></tr></thead><tbody>{readinessAudit.supportedConfirmations.map(row=><tr key={row.playerId}><td>{row.player}</td><td>{display(row.baseRound)}</td><td>{row.tenureYears}</td><td>{row.sourceCells.join(", ")}</td></tr>)}</tbody></table></div></details>
 <details style={{marginTop:20}}><summary style={{cursor:"pointer",fontWeight:700}}>Inspect the {readinessAudit.ruleConfirmedProfiles.length} profiles confirmed by the undrafted rule</summary><p style={{margin:"14px 0",lineHeight:1.8}}>Thirty players went undrafted in 2025 and enter this keeper selection at nominal round 13 with one completed tenure season. Six went undrafted in 2024 and were retained in 2025, so they enter at nominal round 12 with two completed tenure seasons. That same rule confirms Hart and Grimes: their earlier payment picks do not change their nominal cost.</p><div className="table-wrap"><table className="data-table"><thead><tr><th scope="col">Player</th><th scope="col">2026 base</th><th scope="col">Completed tenure</th><th scope="col">Rule &amp; supporting history</th></tr></thead><tbody>{readinessAudit.ruleConfirmedProfiles.map(row=><tr key={row.playerId}><td>{row.player}</td><td>{display(row.baseRound)}</td><td>{row.tenureYears}</td><td>{row.explanation}<span className="cell-note">{row.sourceCells.join(", ")}</span></td></tr>)}</tbody></table></div></details>
 </section>
 <section className="panel" style={{margin:"28px 0",padding:24}}>
 <h2>2025 exceptions</h2>
 <div className="table-wrap"><table className="data-table"><thead><tr><th>Player</th><th>Sheet value</th><th>Calculated</th><th>Source cells</th></tr></thead><tbody>{exceptions.map(row=><tr key={row.player}><td><strong>{row.player}</strong><span className="cell-note">{row.status.replaceAll("_"," ")}</span></td><td>{row.targetVariants.map(t=>display(t.cost)).join(" / ")}</td><td>{display(row.calculated)}</td><td>{row.sourceCells.join(", ")}<span className="cell-note">Target: {row.targetVariants.map(t=>t.sourceCell).join(", ")}</span></td></tr>)}</tbody></table></div>
 <p className="small" style={{marginTop:16}}>Giannis was recorded in round 2 of the 2024 draft, which calculates to a round-1 keeper cost for 2025; the target table says ineligible. Dort appears as both round 11 and round 12. Neither discrepancy is silently corrected.</p>
 </section>
 <section className="panel" style={{padding:24,marginBottom:24}}><h2>Earlier calculations</h2><div className="table-wrap"><table className="data-table"><thead><tr><th>Season</th><th>Method</th><th>Matches</th><th>Differences</th></tr></thead><tbody>{audit.historicalAudits.map((check,i)=><tr key={i}><td>{check.season}</td><td>{check.method==="legacy_previous_round_minus_one"?"Legacy: previous round minus one":"Original round and elapsed tenure"}</td><td>{check.summary.matched} / {check.summary.total}</td><td>{check.summary.mismatched}</td></tr>)}</tbody></table></div><p className="small" style={{marginTop:16}}>The corrected 2024 table includes a round-zero value for Damian Lillard where the rules require ineligibility. The workbook’s legacy calculation is checked separately from corrected nominal costs.</p></section>
 <section className="panel" style={{padding:24,marginBottom:24}}><h2>Upcoming 2026 draft: keeper projection</h2><p>{audit.projection2026.summary.total} final-roster players: <strong>{audit.projection2026.summary.eligible} pass the cost and tenure rules</strong>; {audit.projection2026.summary.ineligible} are ineligible. All cost and tenure reviews in this projection are resolved. Payment still requires an available, owned pick.</p><p style={{marginTop:12}}>Quentin Grimes and Josh Hart are confirmed at nominal round 12 and tenure two. The initial projection flagged seventeen reconstructed keeper tenures; the readiness review above records the evidence and established rule supporting them.</p><p style={{marginTop:12}}>The workbook’s 2026 Draft tab is the workspace for the upcoming draft. Blank player inputs are expected until selections are entered. Upcoming keeper costs are checked against the confirmed rules and frozen roster, using the approved 2025 nominal-cost baseline and commissioner rulings.</p></section>
 <details className="panel" style={{padding:24,marginBottom:24}}><summary style={{cursor:"pointer",fontWeight:700}}>Inspect all {totals.total} historical 2025 comparisons</summary><p style={{margin:"16px 0",lineHeight:1.7}}>Calculated from earlier-season evidence. These comparisons do not rewrite the costs already accepted by the league.</p><div className="table-wrap"><table className="data-table"><thead><tr><th>Player</th><th>2025 target</th><th>Calculated</th><th>Result / evidence</th></tr></thead><tbody>{audit.replay2025.rows.map(row=><tr key={row.player}><td><strong>{row.player}</strong></td><td>{display(row.expected)}</td><td>{display(row.calculated)}</td><td>{row.status.replaceAll("_"," ")}<span className="cell-note">{row.sourceCells.join(", ")}</span></td></tr>)}</tbody></table></div></details>
 <details className="panel" style={{padding:24,marginBottom:24}}><summary style={{cursor:"pointer",fontWeight:700}}>Inspect all 111 projected 2026 keeper costs</summary><p style={{margin:"16px 0",lineHeight:1.7}}>This is the reviewed projection from the March 29 roster. Cost is separate from payment. The initial undrafted season counts as tenure one; each consecutive retention adds one tenure season and advances the nominal keeper cost one round earlier. Historical review flags remain in the source audit without marking these resolved profiles as outstanding.</p><div className="table-wrap"><table className="data-table"><thead><tr><th>Player / franchise</th><th>2025 base</th><th>2025 pick spent</th><th>Tenure</th><th>2026 base</th><th>Review notes</th></tr></thead><tbody>{audit.projection2026.rows.map(row=><tr key={row.espnPlayerId}><td><strong>{row.player}</strong><span className="cell-note">{leagueData.teams.find(t=>String(t.id)===row.franchiseId)?.owner}</span></td><td>{display(row.base2025)}</td><td>{display(row.payment2025)}</td><td>{row.tenureAfter2025 ?? "Unknown"}</td><td>{row.eligible?display(row.base2026):"Ineligible"}</td><td>{[...row.ineligibilityReasons,...row.reviewFlags].map(value=>value.replaceAll("_"," ")).join("; ")||"No cost/tenure exception"}</td></tr>)}</tbody></table></div></details>
 <section className="panel" style={{padding:24}}><h2>What this verifies</h2>{audit.methodology.slice(0,4).map((text,i)=><p key={i} style={{margin:"14px 0",lineHeight:1.6}}>{text}</p>)}<h3 style={{marginTop:24}}>Limits of the historical check</h3><ul style={{paddingLeft:22,lineHeight:1.7}}>{audit.limitations.map((text,i)=><li key={i} style={{margin:"10px 0"}}>{text}</li>)}</ul></section>
 </div>}/>;
}
