import Link from "next/link";
import audit from "../../../data/keeper-audit.json";
import { leagueData } from "../../lib/league-data";
const display=(value:unknown)=>value===null?"Unknown":typeof value==="number"?"Round "+value:String(value).replaceAll("_"," ");
export default function AuditPage() {
 const totals=audit.replay2025.summary;
 const exceptions=audit.replay2025.rows.filter(row=>row.status!=="match");
 return <main style={{maxWidth:1160,margin:"0 auto",padding:"40px 24px 80px"}}>
 <Link className="button button-green" href="/">← Back to the league</Link>
 <p className="eyebrow" style={{marginTop:36}}>HISTORICAL KEEPER CHECK</p>
 <h1 style={{fontSize:"clamp(36px,6vw,64px)",lineHeight:1.1,margin:"10px 0 18px"}}>Show the math.</h1>
 <p style={{maxWidth:800,fontSize:18,lineHeight:1.6}}>Independent calculations reproduce <strong>{totals.matched} of {totals.total}</strong> canonical 2025 keeper-cost records. One record differs and one player has conflicting source costs. Your later rulings remain separate from the historical comparison.</p>
 <section className="panel" style={{margin:"28px 0",padding:24}}>
 <h2>2025 exceptions</h2>
 <div className="table-wrap"><table className="data-table"><thead><tr><th>Player</th><th>Sheet value</th><th>Calculated</th><th>Source cells</th></tr></thead><tbody>{exceptions.map(row=><tr key={row.player}><td><strong>{row.player}</strong><span className="cell-note">{row.status.replaceAll("_"," ")}</span></td><td>{row.targetVariants.map(t=>display(t.cost)).join(" / ")}</td><td>{display(row.calculated)}</td><td>{row.sourceCells.join(", ")}<span className="cell-note">Target: {row.targetVariants.map(t=>t.sourceCell).join(", ")}</span></td></tr>)}</tbody></table></div>
 <p className="small" style={{marginTop:16}}>Giannis was recorded in round 2 of the 2024 draft, which calculates to a round-1 keeper cost for 2025; the target table says ineligible. Dort appears as both round 11 and round 12. Neither discrepancy is silently corrected.</p>
 </section>
 <section className="panel" style={{padding:24,marginBottom:24}}><h2>Earlier calculations</h2><div className="table-wrap"><table className="data-table"><thead><tr><th>Season</th><th>Method</th><th>Matches</th><th>Differences</th></tr></thead><tbody>{audit.historicalAudits.map((check,i)=><tr key={i}><td>{check.season}</td><td>{check.method==="legacy_previous_round_minus_one"?"Legacy: previous round minus one":"Original round and elapsed tenure"}</td><td>{check.summary.matched} / {check.summary.total}</td><td>{check.summary.mismatched}</td></tr>)}</tbody></table></div><p className="small" style={{marginTop:16}}>The corrected 2024 table includes a round-zero value for Damian Lillard where the rules require ineligibility. The workbook’s legacy calculation is checked separately from corrected nominal costs.</p></section>
 <section className="panel" style={{padding:24,marginBottom:24}}><h2>2026 projection</h2><p>{audit.projection2026.summary.total} final-roster players: <strong>{audit.projection2026.summary.eligible} pass the cost and tenure rules</strong>, including {audit.projection2026.summary.provisionalCosts} provisional cost rulings; {audit.projection2026.summary.ineligible} are ineligible. Payment still requires an available, owned pick.</p><p style={{marginTop:12}}>Quentin Grimes and Josh Hart remain provisionally round 12. Seventeen keeper tenures are inferred from the supplied keeper history and labeled in the detailed report.</p><p style={{marginTop:12}}>The workbook’s 2026 tab has blank player inputs and old column labels. It cannot independently confirm the 2026 projection.</p></section>
 <details className="panel" style={{padding:24,marginBottom:24}}><summary style={{cursor:"pointer",fontWeight:700}}>Inspect all {totals.total} historical 2025 comparisons</summary><p style={{margin:"16px 0",lineHeight:1.7}}>Calculated from earlier-season evidence. These comparisons do not rewrite the costs already accepted by the league.</p><div className="table-wrap"><table className="data-table"><thead><tr><th>Player</th><th>2025 target</th><th>Calculated</th><th>Result / evidence</th></tr></thead><tbody>{audit.replay2025.rows.map(row=><tr key={row.player}><td><strong>{row.player}</strong></td><td>{display(row.expected)}</td><td>{display(row.calculated)}</td><td>{row.status.replaceAll("_"," ")}<span className="cell-note">{row.sourceCells.join(", ")}</span></td></tr>)}</tbody></table></div></details>
 <details className="panel" style={{padding:24,marginBottom:24}}><summary style={{cursor:"pointer",fontWeight:700}}>Inspect all 111 projected 2026 keeper costs</summary><p style={{margin:"16px 0",lineHeight:1.7}}>This is the migration projection from the March 29 roster, before future commissioner edits. Cost is separate from payment. The initial tenure value for 30 undrafted players is a stated convention awaiting review.</p><div className="table-wrap"><table className="data-table"><thead><tr><th>Player / franchise</th><th>2025 base</th><th>2025 pick spent</th><th>Tenure</th><th>2026 base</th><th>Review notes</th></tr></thead><tbody>{audit.projection2026.rows.map(row=><tr key={row.espnPlayerId}><td><strong>{row.player}</strong><span className="cell-note">{leagueData.teams.find(t=>String(t.id)===row.franchiseId)?.owner}</span></td><td>{display(row.base2025)}</td><td>{display(row.payment2025)}</td><td>{row.tenureAfter2025 ?? "Unknown"}</td><td>{row.eligible?display(row.base2026):"Ineligible"}</td><td>{[...row.ineligibilityReasons,...row.reviewFlags].map(value=>value.replaceAll("_"," ")).join("; ")||"No cost/tenure exception"}</td></tr>)}</tbody></table></div></details>
 <section className="panel" style={{padding:24}}><h2>What this verifies</h2>{audit.methodology.slice(0,4).map((text,i)=><p key={i} style={{margin:"14px 0",lineHeight:1.6}}>{text}</p>)}<h3 style={{marginTop:24}}>Limits of the historical check</h3><ul style={{paddingLeft:22,lineHeight:1.7}}>{audit.limitations.map((text,i)=><li key={i} style={{margin:"10px 0"}}>{text}</li>)}</ul></section>
 </main>;
}
